### ISSUE TITLE
ASSERT_EQ in HatchitMath tests

### ISSUE THREAD

**Issue by MattGuerrette** [thirddegree/HatchitMath#3]
You may want to use EXPECT_EQ rather than ASSERT_EQ as the former will allow the tests to continue running. ASSERT i believe will hard exit the testcase

**Comment by Honeybunch** [comment]
I thought I replied to this on mobile. My bad.

This can be something we discuss but so far I thin that ASSERT_EQ is fine for most of the tests so far. Personally I feel that if I'm testing the output vector of a calculation and one element of the vector is wrong then I don't need the test to continue. Some of the larger more thorough tests may want EXPECT_EQ to be used instead and if that's a change that we want to see that's fine by me.
